// Generated by Wrangler on Sat Jun 08 2024 01:09:29 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	SENDER: {"name":"Contact Mail Sender","addr":"sender@example.jp"};
	RECIPIENT: {"name":"Contact Mail Recipient","addr":"recipient@example.jp"};
	SEB: SendEmail;
}
