#:schema node_modules/wrangler/config-schema.json
name = "sendmail-worker-example"
main = "src/index.ts"
compatibility_date = "2024-06-05"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

send_email = [
	{ name = "SEB" },
]

[vars]
SENDER = { name = "Contact Mail Sender", addr = "sender@example.jp" }
RECIPIENT = { name = "Contact Mail Recipient", addr = "recipient@example.jp" }
